# Site settings
title:          Growth through documentation
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://hocaron.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Hocaron
  url:          https://hocaron.github.io
  email:        kkannu0407@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-polyglot
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Plugin
languages: ["ko", "en"]
default_lang: "en"
exclude_from_localization: ["javascript","images","css"]
parallel_localization: true

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
